version: '3'
  
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile  
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - "./:/twitter/"
  
  postgres:
    image: postgres:15.2
    restart: unless-stopped
    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=twitter
      - TZ=Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - "./db/postgres_data:/var/lib/postgresql/data"
        
  redis:
    image: redis:7.0.10
    restart: unless-stopped
      
    ports:
      - "6379:6379"
    
    volumes:
      - "./db/redis_data:/var/lib/redis/data"


volumes:
  twitter:
  postgres_data:
  redis_data: